#Load in numpy

In [1]:
import numpy as np

# The basics

In [12]:
a = np.array([1,2,3], dtype= 'int16')
a

array([1, 2, 3], dtype=int16)

In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [13]:
#get type
a.dtype

dtype('int16')

In [15]:
#Get size
b.itemsize

8

In [17]:
# Get the total size
a.nbytes

6

# Accessing/Changing specific element, rows, columns, etc

In [18]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#Get a specific element [r, c]:
a[1, -2]

13

In [22]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#Get a specific column
a[:, 0]

array([1, 8])

In [24]:
# Getting a little more fancy [row , startindex:ending index:Stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [26]:
#replacing value
a[1,5] = 20
print(a)

a[:, 2]= 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3D example

In [27]:
b= np.array([[[1,2], [3,4]],[[5,6], [6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [28]:
#Get a specific element (Work outside in) [Matrix, row, column]
b[0, 0, 1]

2

In [31]:
# replace (as long as it's the same dimention it's going to work)
b[:,1,:] = [[9,8], [8,9]]
print(b)

[[[1 2]
  [9 8]]

 [[5 6]
  [8 9]]]


# Initializing different types of arrays

In [32]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
# All ones matrix
np.ones((2,3), dtype= 'int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [35]:
#Any other number
np.full((2,2), 99, dtype= 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [36]:
#Any other number (full like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal number
np.random.rand(4,2)

array([[0.58682151, 0.90222885],
       [0.43498334, 0.46951578],
       [0.60601948, 0.64046913],
       [0.50075831, 0.0763016 ]])

In [43]:
# Random Demimal number
np.random.rand(4,2)

array([[0.06060485, 0.57891007],
       [0.2485443 , 0.29472041],
       [0.87998506, 0.20244008],
       [0.81726562, 0.0378958 ]])

In [41]:
# Random integer value np.random.randint(end_number exlusive, size =(r, c))
np.random.randint(7, size= (3,3))

array([[6, 6, 1],
       [3, 5, 6],
       [0, 2, 4]])

In [47]:
# Random integer value np.random.randint(start_num, end_number exlusive, size =(r, c))
np.random.randint(3,7, size= (3,3))

array([[5, 4, 5],
       [3, 4, 5],
       [3, 6, 6]])

In [48]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
# Be careful when copying arrays
a =