#Load in numpy

In [ ]:
import numpy as np

# The basics

In [ ]:
a = np.array([1,2,3], dtype= 'int16')
a

array([1, 2, 3], dtype=int16)

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
#get type
a.dtype

dtype('int16')

In [ ]:
#Get size
b.itemsize

8

In [ ]:
# Get the total size
a.nbytes

6

# Accessing/Changing specific element, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element [r, c]:
a[1, -2]

13

In [ ]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column
a[:, 0]

array([1, 8])

In [ ]:
# Getting a little more fancy [row , startindex:ending index:Stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
#replacing value
a[1,5] = 20
print(a)

a[:, 2]= 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3D example

In [ ]:
b= np.array([[[1,2], [3,4]],[[5,6], [6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [ ]:
#Get a specific element (Work outside in) [Matrix, row, column]
b[0, 0, 1]

2

In [ ]:
# replace (as long as it's the same dimention it's going to work)
b[:,1,:] = [[9,8], [8,9]]
print(b)

[[[1 2]
  [9 8]]

 [[5 6]
  [8 9]]]


# Initializing different types of arrays

In [ ]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# All ones matrix
np.ones((2,3), dtype= 'int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [ ]:
#Any other number
np.full((2,2), 99, dtype= 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
#Any other number (full like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal number
np.random.rand(4,2)

array([[0.32269226, 0.26234379],
       [0.34849023, 0.42882281],
       [0.27431739, 0.62286905],
       [0.1817244 , 0.64380613]])

In [ ]:
# Random Demimal number
np.random.rand(4,2)

array([[0.53854517, 0.43208198],
       [0.91485066, 0.40241367],
       [0.06993465, 0.05581012],
       [0.11872267, 0.7565908 ]])

In [ ]:
# Random integer value np.random.randint(end_number exlusive, size =(r, c))
np.random.randint(7, size= (3,3))

array([[6, 5, 6],
       [4, 1, 5],
       [6, 1, 3]])

In [ ]:
# Random integer value np.random.randint(start_num, end_number exlusive, size =(r, c))
np.random.randint(3,7, size= (3,3))

array([[3, 5, 5],
       [4, 4, 6],
       [4, 3, 3]])

In [ ]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
# Be careful when copying arrays
a = np.array([1,2,3])
b= a
b[0] = 100

print(a)

[100   2   3]


# Mathematics

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a/ 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a**2

array([ 1,  4,  9, 16])

In [ ]:
# take the sine and cosine
print(np.sin(a))

print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


**Linear Algebra **

In [ ]:
#matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#find the determinent
c = np.identity(3)

np.linalg.det(c)

1.0

**statistics**

In [ ]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#find the minimum
np.min(stats, axis = 1)

array([1, 4])

In [ ]:
#Find the maximum
np.max(stats)

6

In [ ]:
np.sum(stats)

21

# Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4], [4,5,6,7]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
#verticaly staking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Herizontal stacking
h1 = np.ones((2,3))
h2 = np.zeros((2,3))

np.hstack((h1,h2))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

# Credit to

Youtube video: https://www.youtube.com/watch?v=QUT1VHiLmmI